TASK_NAME: 'Deeplabv3_Mapillary'
AUTO_RESUME: true
RESUME_STATES: true

MODEL:
  TYPE: 'DeepLabv3+'
  WEIGHT: ''
  SYNC_BN: false

DATASET:
  NAME: "Mapillary"
  IN_CHANNELS: 0
  NUM_CLASSES: 0
  ROOT_DIR: '/avl-west/Mapillary'
  TRAIN: ''
  VAL: ''
  TEST: ''

DATALOADER:
  NUM_WORKERS: 0
  DROP_LAST: true
  PIN_MEMORY: true

OPTIMIZER:
  TYPE: 'SGD'
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0
  MAX_GRAD_NORM: 0
  SGD:
    momentum: 0.0
    dampening: 0.0
    nesterov: false
  Adam:
    betas: [0.9, 0.999]

SCHEDULER:
  TYPE: 'PolyLRDecay'
  MAX_EPOCH: 1
  CLIP_LR: 0.0
  StepLR:
    step_size: 0
    gamma: 0.1
  MultiStepLR:
    milestones: []
    gamma: 0.1
  PolyLRDecay:
    max_iter: 300
    power: 0.9

TRAIN:
  BATCH_SIZE: 1
  CHECKPOINT_PERIOD: 0
  LOG_PERIOD: 0
  AUGMENTATION: []
  FROZEN_PATTERNS: []
  FREEZE_BATCHNORM: false

VALIDATE:
  BATCH_SIZE: 1
  PERIOD: 0
  LOG_PERIOD: 0
  METRIC: ''
  AUGMENTATION: []

TEST:
  BATCH_SIZE: 1
  LOG_PERIOD: 0
  WEIGHT: ''
  AUGMENTATION: []

OUTPUT_DIR: '@'
RNG_SEED: -1
